<?php

namespace AppBundle\Repository;

/**
 * messurementUnitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messurementUnitsRepository extends \Doctrine\ORM\EntityRepository
{
}
