messurementunits_index:
    path:     /
    defaults: { _controller: "AppBundle:messurementUnits:index" }
    methods:  GET

messurementunits_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:messurementUnits:show" }
    methods:  GET

messurementunits_new:
    path:     /new
    defaults: { _controller: "AppBundle:messurementUnits:new" }
    methods:  [GET, POST]

messurementunits_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:messurementUnits:edit" }
    methods:  [GET, POST]

messurementunits_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:messurementUnits:delete" }
    methods:  DELETE
